name: example
description: "An example project using Kilobyte 3D."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  kilobyte_3d:
    path: ..
  vector_math: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
