name: kilobyte_3d
description: "A lightweight software 3D rendering engine for Flutter using CustomPainter."
version: 0.0.1
homepage:

environment:
  sdk: ^3.10.8
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
