import 'dart:ui';

/// Represents a projected vertex inside viewport space.
///
/// A viewport vertex stores the final screen-space position generated by the projection pipeline alongside its depth
/// relative to the camera.
class ProjectedVertex {

  /// The final 2D screen-space position.
  final Offset position;

  /// The camera-space depth value.
  ///
  /// Positive values are located in front of the camera.
  /// Negative values typically indicate vertices behind the near plane.
  final double depth;

  const ProjectedVertex({
    this.position = Offset.zero,
    this.depth = 0.0,
  });
}
